spring:
  application:
    name: turbine
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka1:8761/eureka/,http://root:root@eureka2:8762/eureka/,http://root:root@eureka3:8763/eureka/

turbine:
  app-config: order
  clusterNameExpression: new String("default")
