spring:
  application:
    name: gateway
  cloud:
    config:
      username: root
      password: root
      discovery:
        enabled: true
        service-id: config-server

    gateway:
      discovery:
        locator:
          #Flag that enables DiscoveryClient gateway integration
          enabled: true
          #Option to lower case serviceId in predicates and filters, defaults to false.
          #Useful with eureka when it automatically uppercases serviceId. so MYSERIVCE, would match /myservice/**
          lowerCaseServiceId: true
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka1:8761/eureka/,http://root:root@eureka2:8762/eureka/,http://root:root@eureka3:8763/eureka/








