spring:
  application:
    name: eureka
  security:
    user:
      name: muyun
      password: muyun

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



