spring:
  application:
    name: config-server

  #active profile must be native,because classpath:/config is be used
  #  profiles:
  #    active: native
  #    cloud:
  #      config:
  #        server:
  #          native:
  #            searchLocations:
  security:
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mu-yun/spring-cloud.git
          search-paths: config/
    bus:
      trace:
        enabled: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka1:8761/eureka/,http://root:root@eureka2:8762/eureka/,http://root:root@eureka3:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env
